限制性内切酶DNase I（Deoxyribonuclease I），是一种可以消化单链或双链DNA产生单脱氧核苷酸或单链或双链的寡脱氧核苷酸的核酸内切酶。

DNase-seq 利用DNase I的特性对样品进行了片段化处理，在染色质致密区域，DNA链被致密结构很好地保护起来，使得内切酶无法接近这些区域，只能切割开放区域的DNA。在开放区域，缠绕在核小体上的DNA被核小体结构所保护，只有核小体之间的DNA序列能够被DNase I切割，这些区域内能够被DNase切割的位点也被称为DHS，即DNase超敏感位点（DNase hypersensitive sites）。对被切割后的序列进行捕获，建库和测序，就能很好的了解开放染色质的区域。
